cmake cache debug print

diff --git a/.github/workflows/build-check.yaml b/.github/workflows/build-check.yaml
--- a/.github/workflows/build-check.yaml
+++ b/.github/workflows/build-check.yaml
@@ -21,6 +21,10 @@ jobs:
           fetch-depth: 0
           token: ${{ secrets.PAT_TOKEN }}
 
+      - name: Check cache existence before
+        run: |
+          cat ${{ github.workspace }}/build/external/wxWidgets/CMakeCache.txt || echo "CMakeCache.txt missing"
+
       - name: Cache External Builds
         uses: actions/cache@v3
         with:
@@ -37,6 +41,10 @@ jobs:
             }}
           restore-keys: |
             ${{ runner.os }}-external-
+
+      - name: Check cache existence after
+        run: |
+          cat ${{ github.workspace }}/build/external/wxWidgets/CMakeCache.txt || echo "CMakeCache.txt missing"
 
       - name: Install Dependencies
         run: |
