verbatim local command

diff --git a/.github/workflows/clang-tidy-check.yaml b/.github/workflows/clang-tidy-check.yaml
--- a/.github/workflows/clang-tidy-check.yaml
+++ b/.github/workflows/clang-tidy-check.yaml
@@ -23,11 +23,8 @@ jobs:
 
       - name: Install clang-tidy and dependencies
         run: |
-          wget https://apt.llvm.org/llvm.sh
-          chmod +x llvm.sh
-          sudo ./llvm.sh 19
-          sudo apt-get install -y clang-tidy-19
-          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-19 100
+          sudo apt-get update
+          sudo apt-get install -y clang-tidy
 
       - name: Verify .clang-tidy exists
         run: |
@@ -57,16 +54,17 @@ jobs:
 
       - name: Run clang-tidy
         run: |
-          TIDY_ISSUES=0
-          for file in $(find ./src -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \)); do
-            echo "Analyzing $file..."
-            if ! clang-tidy "$file" -p . > tidy_output.txt 2>&1; then
-              TIDY_ISSUES=1
-              echo "::error::Clang-tidy issues found in $file"
-              cat tidy_output.txt
-            fi
-          done
-          if [ $TIDY_ISSUES -ne 0 ]; then
+          clang-tidy src/*.cpp src/*.h src/*.hpp -p compile_commands.json
+          #TIDY_ISSUES=0
+          #for file in $(find ./src -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \)); do
+          #  echo "Analyzing $file..."
+          #  if ! clang-tidy "$file" -p . > tidy_output.txt 2>&1; then
+          #    TIDY_ISSUES=1
+          #    echo "::error::Clang-tidy issues found in $file"
+          #    cat tidy_output.txt
+          #  fi
+          #done
+          if [ $? -ne 0 ]; then
             echo "Static analysis check failed. Please fix the issues reported by clang-tidy."
             exit 1
           else
